# Basic Tensorflow Syntax

In [1]:
import tensorflow as tf

In [3]:
#Printing Version
print(tf.__version__)

1.13.1


In [4]:
hello = tf.constant('Hello ')

In [5]:
world = tf.constant('World')

In [6]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [7]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [10]:
with tf.Session() as sess:
    result = sess.run(hello + world)

In [11]:
print(result)

b'Hello World'


In [12]:
a = tf.constant(10)

In [13]:
b = tf.constant(20)

In [14]:
with tf.Session() as sess:
    result = sess.run(a + b)

In [15]:
print(result)

30


In [17]:
const = tf.constant(10)

In [18]:
fill_mat = tf.fill((4,4), 10)

In [19]:
myzeros = tf.zeros((4,4))

In [20]:
myones = tf.ones((4,4))

In [21]:
myrandn = tf.random_normal((4,4),mean=0,stddev=1.0)

In [22]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [23]:
allOps = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [24]:
sess = tf.InteractiveSession()

In [25]:
for op in allOps:
    print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.02216499 -1.0117469  -0.37802622 -0.33655593]
 [ 0.8069386   0.867094   -1.4192082  -0.2602531 ]
 [-0.05648338 -0.27979442 -0.24204221 -2.4013915 ]
 [ 0.02367096 -0.1900768   0.41851598 -1.1448598 ]]


[[0.18862593 0.7775518  0.5271424  0.06977558]
 [0.10088587 0.96885157 0.1265353  0.08081436]
 [0.9613172  0.20895004 0.47579086 0.775525  ]
 [0.44713485 0.8869208  0.45362794 0.60750556]]




In [26]:
for op in allOps:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.979053    0.36117494  0.60798174 -0.44826007]
 [ 0.2650327  -0.6687648   0.06239221  1.1420469 ]
 [ 0.06780185 -0.34770405 -0.7336649   0.17685947]
 [-0.2894672   0.79282    -0.1540292   0.31691694]]


[[0.5285717  0.535686   0.84079075 0.15549433]
 [0.7295425  0.60416067 0.8857062  0.9815041 ]
 [0.9239807  0.47785842 0.7968817  0.5597801 ]
 [0.06440914 0.54483914 0.79972434 0.87921274]]




In [27]:
a = tf.constant([ [1,2],
                  [3,4] ])
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [28]:
b = tf.constant([ [10],
                  [100 ]])
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [ ]:
result = 